# Development Tools
brew "git"
brew "gh"
brew "go"
brew "python3"
brew "uv"
brew "node" # npm-backed Mason language servers
brew "neovim"
brew "tree-sitter-cli"
brew "shfmt"
brew "git-delta"
brew "git-lfs"
brew "tlrc"
brew "glow"
brew "direnv"
tap "can1357/tap"
brew "can1357/tap/omp"

# System Utilities
brew "coreutils"
brew "findutils"
brew "gnu-sed"
brew "curl"
brew "wget"
brew "parallel"
brew "watch"
brew "tree"
brew "btop"
brew "ncdu"
brew "lnav"
brew "topgrade"
brew "stow"
brew "bat"
brew "pv"
brew "syncthing", restart_service: :changed
brew "nmap"
brew "mtr"
tap "teamookla/speedtest"
brew "teamookla/speedtest/speedtest"
tap "buo/cask-upgrade"


# Shell & Navigation
brew "zsh"
brew "tmux"
brew "fzf"
brew "zoxide"
brew "fd"
brew "eza"
brew "ripgrep"
brew "jq"
brew "jless"
brew "yazi"
brew "llm"
brew "herdr"
# Container & Cloud
brew "kubernetes-cli"
brew "helm"
brew "kubectx"
brew "krew"
brew "kind"
brew "colima"
brew "docker"
brew "docker-compose"

# Desktop Applications
cask "ghostty@tip"
cask "slack"
cask "spotify"
cask "plexamp"
cask "telegram-desktop"
cask "1password"
cask "discord"
cask "obsidian"
cask "claude-code"
cask "cursor-cli"
cask "zed"
cask "font-hack-nerd-font"
cask "font-fira-code-nerd-font"
