# Development Tools
brew "git"
brew "gh"
brew "go"
brew "python3"
brew "uv"
brew "node" # npm-backed Mason language servers
brew "neovim"
brew "tree-sitter-cli"
brew "shfmt"
brew "git-delta"
brew "git-lfs"
brew "tlrc"
brew "glow"
brew "direnv"
tap "can1357/tap"
brew "can1357/tap/omp"
tap "cormacrelf/tap"
brew "cormacrelf/tap/dark-notify"
tap "terraform-linters/tap"
cask "terraform-linters/tap/tflint"
cask "visual-studio-code"
cask "cursor"

# System Utilities
brew "coreutils"
brew "findutils"
brew "gnu-sed"
brew "curl"
brew "wget"
brew "parallel"
brew "watch"
brew "tree"
brew "btop"
brew "ncdu"
brew "lnav"
brew "topgrade"
brew "stow"
brew "bat"
brew "pv"
tap "teamookla/speedtest"
brew "teamookla/speedtest/speedtest"
tap "buo/cask-upgrade"


# Shell & Navigation
brew "zsh"
brew "tmux"
brew "fzf"
brew "zoxide"
brew "fd"
brew "eza"
brew "ripgrep"
brew "jq"
brew "jless"
brew "llm"

# Container & Cloud
brew "kubernetes-cli"
brew "helm"
brew "kubectx"
brew "krew"
brew "kind"
cask "docker-desktop"
brew "az"

# Desktop Applications
cask "alfred"
cask "ghostty@tip"
cask "slack"
cask "spotify"
cask "plexamp"
cask "bartender"
cask "telegram"
cask "1password"
cask "discord"
cask "obsidian"
cask "home-assistant"
cask "monitorcontrol"
cask "meetingbar"
cask "font-hack-nerd-font"
cask "font-fira-code-nerd-font"
